server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  absolute_redirect off;

  location = / {
    return 301 /sms/;
  }

  location /sms/ {
    rewrite ^/sms/(.*)$ /$1 break;
    try_files $uri $uri/ /index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
